### ISSUE TITLE
Restarting pipeline midway through?

### ISSUE THREAD

**Issue by blin100** [Zhang-lab/ATAC-seq_QC_analysis#6]
Hi, thanks for creating this wonderful tool, I was wondering if it's possible to resume the pipeline midway through? So for example, if it finishes trimming and mapping, but ends unexpectedly, can I feed in the completed mapped files for it to restart from that point, and not redo the whole pipeline?

My reason for this is that my input files are extremely large, and even after 3 days of running on the cluster, it barely finishes mapping, and then my cluster time ends. I'd like to restart this if possible.

Thanks!

**Comment by ShaopengLiu1** [comment]
Hi, 

Sorry I didn't make the analysis in an object-oriented way (still a bad programmer), and each step will have many dependent variables from the prior.

Could you try nohup to run your job on the cluster, or your continuous using time is limited to 3 days?

**Comment by blin100** [comment]
Ahh, gotcha, not a problem! For other users who may run into questions about runtime and resource usage:
My input was PE 150bp reads, 120M reads:
Runtime of 2 days, 10 hours, using 23 gb of ram on 20 cores.

Thanks!
