### ISSUE TITLE
can not open some links in the doucument page

### ISSUE THREAD

**Issue by lin-zhongbao** [Zhang-lab/ATAC-seq_QC_analysis#9]
Hi!
    May you check the documentation page:
https://github.com/Zhang-lab/ATAC-seq_QC_analysis/blob/master/documents/Documentation.md

when I click the link for: "output image" / "QC image" / "Plot collection"

I got the error information: "Cannot proxy the given URL", so there maybe something wrong.

I just want to see how these plots look like.

**Comment by ShaopengLiu1** [comment]
Hi Zhongbao, thanks for the notification! Our FTP server has been changed last year so the link is broken now. We will replace a new link soon : ) Sorry for the inconvenience.

**Comment by ShaopengLiu1** [comment]
Figures updated, thanks for your notification!
